# test
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.15.1
    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "../yarn.lock" }}

      - run:
          name: install dependencies
          command: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  test:
    docker:
      - image: cimg/node:16.15.1
    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "../yarn.lock" }}

      - run:
          name: unit test
          command: yarn test

workflows:
  my-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

      - test:
          filters:
            branches:
              only: -main
