# test
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.15.1 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: install dependencies
          command: yarn install

  test:
    docker:
      - image: cimg/node:16.15.1 # the primary container, where your job's commands are run
    steps:
      - checkout
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: unit test
          command: yarn test

workflows:
  my-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

      - test:
          filters:
            branches:
              only: -main
